# Generated by Django 4.0.2 on 2022-02-19 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Last1month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('superchat_total', models.IntegerField(blank=True, default=0)),
                ('subscriber_total', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Tops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('order', models.IntegerField(max_length=3)),
                ('name', models.CharField(max_length=100, null=True)),
                ('superchat_tops', models.IntegerField(blank=True, default=0)),
                ('subscriber_tops', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(default=datetime.date(2022, 2, 19))),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('img', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('daytime', models.DateTimeField(max_length=4)),
                ('superchat_total', models.IntegerField()),
                ('subscriber_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('img', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('superchat_total', models.IntegerField(default=0)),
                ('superchat_daily', models.IntegerField(blank=True, default=0)),
                ('superchat_weekly', models.IntegerField(blank=True, default=0)),
                ('superchat_monthly', models.IntegerField(blank=True, default=0)),
                ('subscriber_total', models.IntegerField(max_length=10)),
                ('subscriber_daily', models.IntegerField(blank=True, default=0)),
                ('subscriber_weekly', models.IntegerField(blank=True, default=0)),
                ('subscriber_monthly', models.IntegerField(blank=True, default=0)),
                ('discription', models.TextField(blank=True, default='システムによる記載待ち', max_length=3000)),
                ('tagcheck', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='LiveRank.Tags')),
            ],
        ),
    ]
