# Generated by Django 4.0.2 on 2022-02-21 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_last1month',
            name='last_update',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AddField(
            model_name='main_last1month',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main',
            name='subscriber_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='main_tops',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_update',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
    ]
