# Generated by Django 4.0.2 on 2022-02-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0002_main_last1month_last_update_main_last1month_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_last1month',
            old_name='superchat_total',
            new_name='superchat_daily',
        ),
    ]
