# Generated by Django 4.0.2 on 2022-02-21 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0003_rename_superchat_total_main_last1month_superchat_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='LastUpdate_SuperchatPast',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='main',
            name='superchat_past',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
