# Generated by Django 4.0.2 on 2022-02-25 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0004_main_lastupdate_superchatpast_main_superchat_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_last1month',
            name='number',
        ),
        migrations.AlterField(
            model_name='master',
            name='last_update',
            field=models.DateField(default=datetime.date(2022, 2, 26)),
        ),
    ]
