# Generated by Django 4.0.2 on 2022-03-07 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0005_remove_main_last1month_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='last_update',
            field=models.DateField(default=datetime.date(2022, 3, 7)),
        ),
    ]
