# Generated by Django 3.2.12 on 2022-04-16 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0006_alter_master_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_last1month',
            old_name='last_update',
            new_name='superchat_lastupdate',
        ),
        migrations.AddField(
            model_name='main_last1month',
            name='subscriber_lastupdate',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_update',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
