# Generated by Django 3.2.5 on 2022-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0007_auto_20220416_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
