# Generated by Django 3.2.5 on 2023-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0010_auto_20220813_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubi_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル')),
            ],
        ),
    ]
