# Generated by Django 3.2.5 on 2023-07-11 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0011_ubi_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubi_video',
            name='video',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['.mpg', '.mpeg', '.mp4', '.webm', '.mov', '.avi'])], verbose_name='添付ファイル'),
        ),
    ]
