# Generated by Django 3.2.5 on 2023-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveRank', '0018_alter_ubi_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubi_video',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
