# Generated by Django 4.2.3 on 2023-07-20 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiveRank", "0021_ubi_user_alter_ubi_video_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="ubi_user",
            name="start_time",
            field=models.DateTimeField(default=datetime.date(2020, 1, 1)),
        ),
    ]
